### Find By Id Success
GET {{host}}/api/v1/users/1
Accept: application/json
Authorization: Bearer {{token}}


### Find By Id Failed
GET {{host}}/api/v1/users/100
Accept: application/json
Authorization: Bearer {{token}}

### Login Success
POST {{host}}/api/auth/login
Content-Type: application/json
Accept: application/json

    {
        "email": "anjayxx800@gmail.com",
        "password": "sangatganteng924"
    }

### Login Failed
POST {{host}}/api/auth/login
Content-Type: application/json
Accept: application/json

    {
        "email": "test@gmail.com",
        "password": "test"
    }

### Register Success
POST {{host}}/api/auth/register
Content-Type: application/json
Accept: application/json

    {
        "username": "ariefgantengsekaxli{{$randomInt}}",
        "email": "anjayxx{{$randomInt}}@gmail.com",
        "password": "sangatganteng{{$randomInt}}"
    }

### Register Failed
POST {{host}}/api/auth/register
Content-Type: application/json
Accept: application/json

    {
        "username": "ariefgantengsekali{{$randomInt}}",
        "email": "admin@gmail.com",
        "password": "sangatganteng{{$randomInt}}"
    }

### Find Todo By Id user
GET {{host}}/api/v1/todos
Accept: application/json
Authorization: Bearer {{token}}
