### Register Success
POST {{host}}/api/v1/users
Content-Type: application/json
Accept: application/json

    {
        "username": "ariefgnatengx",
        "password": "ariefgnatengx",
        "email": "ariefgnatengx@gmail.com"
    }

### Register Failed
POST {{host}}/api/v1/users
Content-Type: application/json
Accept: application/json

    {
        "username": "abc",
        "password": "aaa",
        "email": "aaaa"
    }

### Find By Id Success
GET {{host}}/api/v1/users/1
Accept: application/json


### Find By Id Failed
GET {{host}}/api/v1/users/100
Accept: application/json

### Login Success
POST {{host}}/api/v1/login
Content-Type: application/json
Accept: application/json

    {
        "email": "admin@gmail.com",
        "password": "admin"
    }

### Login Failed
POST {{host}}/api/v1/login
Content-Type: application/json
Accept: application/json

    {
        "email": "test@gmail.com",
        "password": "test"
    }